---
- name: Install python3 package
  ansible.builtin.raw: opkg update && opkg install python3
  register: router_python3_install
  changed_when: "'Installing python3' in router_python3_install.stdout"

- name: Deploy dnsmasq configuration
  ansible.builtin.copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart dnsmasq
