---
- name: Update package lists with opkg
  ansible.builtin.raw: opkg update
  changed_when: true

- name: Install python3-light package
  ansible.builtin.raw: opkg install python3-light
  register: router_python3_install
  changed_when: "'Installing python3-light' in router_python3_install.stdout"

- name: Deploy dnsmasq configuration
  ansible.builtin.copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart dnsmasq
