---
- name: Install Flatcar Container Linux
  hosts: rescue
  become: true
  vars:
    flatcar_url_base: "https://raw.githubusercontent.com/flatcar/init/"
    flatcar_url_sha: "3d2f9c6d778b96b08ee7db661bb2af1a6a42679d" # dcf668ed485a9fd278273eb3214449bff3a4a83a
    flatcar_url_path: "/bin/flatcar-install"
  pre_tasks:
    - name: Get target host name from inventory
      ansible.builtin.set_fact:
        target_host: "{{ inventory_hostname }}"
      delegate_to: localhost
      run_once: true

    - name: Generate ignition file with Butane
      ansible.builtin.shell:
        cmd: |
          "docker run --rm -i quay.io/coreos/butane:latest < ../flatcar/butane/{{ target_host }}.yml > ../flatcar/ignition/{{ target_host }}.json"
          npx prettier --write ../flatcar/ignition/{{ target_host }}.json
      args:
        chdir: "{{ playbook_dir }}"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Check if HEAD script matches SHA-locked version
      delegate_to: localhost
      become: false
      block:
        - name: Create temporary directory for script comparison
          ansible.builtin.tempfile:
            state: directory
            suffix: flatcar-check
          register: compare_dir
          check_mode: false

        - name: Download flatcar-install from HEAD
          ansible.builtin.get_url:
            url: "{{ flatcar_url_base }}HEAD{{ flatcar_url_path }}"
            dest: "{{ compare_dir.path }}/flatcar-install"
            mode: "0644"
          check_mode: false

        - name: Download flatcar-install from SHA
          ansible.builtin.get_url:
            url: "{{ flatcar_url_base }}{{ flatcar_url_sha }}{{ flatcar_url_path }}"
            dest: "{{ compare_dir.path }}/flatcar-install"
            mode: "0644"
          notify: Prompt for confirmation on SHA mismatch
          check_mode: false

        - name: Clean up temporary directory
          ansible.builtin.file:
            path: "{{ compare_dir.path }}"
            state: absent

  handlers:
    - name: Prompt for confirmation on SHA mismatch
      ansible.builtin.pause:
        prompt: "The SHA-locked flatcar-install script is out-of-date with HEAD. Press enter to continue or Ctrl+C to abort"
      listen: Prompt for confirmation on SHA mismatch

  tasks:
    - name: Update package repositories
      community.general.apk:
        update_cache: true

    - name: Install flatcar-install script dependencies
      community.general.apk:
        name:
          - bash
          - bzip2
          - util-linux
          - wget
          - coreutils
          - eudev
          - gnupg
          - gawk
          - btrfs-progs-extra
          - wipefs
        state: present

    - name: Find largest disk
      ansible.builtin.set_fact:
        largest_disk: >-
          {{ ansible_devices | dict2items |
            selectattr('value.sectors', 'defined') |
            rejectattr('value.sectors', 'equalto', '0') |
            rejectattr('key', 'match', '^(loop|ram).*') |
            sort(attribute='value.sectors', reverse=true) |
            first }}

    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: flatcar-install
      register: temp_dir

    - name: Download the SHA-locked flatcar-install script to the temporary directory
      ansible.builtin.get_url:
        url: "{{ flatcar_url_base }}{{ flatcar_url_sha }}{{ flatcar_url_path }}"
        dest: "{{ temp_dir.path }}/flatcar-install"
        mode: "0755"
      register: flatcar_script

    - name: Copy ignition file to remote system
      ansible.builtin.copy:
        src: "../flatcar/ignition/{{ target_host }}.json"
        dest: "{{ temp_dir.path }}/ignition.json"
        mode: "0644"

    - name: Wipe disk before installation
      ansible.builtin.command:
        cmd: "wipefs -a /dev/{{ largest_disk.key }}"
      changed_when: true

    - name: Run flatcar-install script with the largest disk
      ansible.builtin.command:
        cmd: "{{ temp_dir.path }}/flatcar-install -v -d /dev/{{ largest_disk.key }} -C stable -i {{ temp_dir.path }}/ignition.json"
      register: install_result
      changed_when: true

    - name: Display installation result
      ansible.builtin.debug:
        var: install_result.stdout_lines

    - name: Install efibootmgr
      community.general.apk:
        name: efibootmgr
        state: present

    - name: Get current EFI boot entries
      ansible.builtin.command:
        cmd: "efibootmgr -v"
      register: efi_boot_entries
      changed_when: false

    - name: Display current EFI boot entries
      ansible.builtin.debug:
        var: efi_boot_entries.stdout_lines

    - name: Parse and delete all existing boot entries
      ansible.builtin.shell:
        cmd: |
          for bootnum in $(efibootmgr | grep -o "Boot[0-9][0-9][0-9][0-9]" | cut -c5-8); do
            efibootmgr -b $bootnum -B
          done
      register: delete_boot_entries
      changed_when: delete_boot_entries.stdout != ""
      failed_when: false # Don't fail if there are no entries to delete

    - name: Copy EFI partition finder script
      ansible.builtin.copy:
        src: scripts/find-efi-partition.sh
        dest: "{{ temp_dir.path }}/find-efi-partition.sh"
        mode: "0755"

    - name: Copy Flatcar boot entry creator script
      ansible.builtin.copy:
        src: scripts/create-flatcar-boot.sh
        dest: "{{ temp_dir.path }}/create-flatcar-boot.sh"
        mode: "0755"

    - name: Find EFI partition on installed system
      ansible.builtin.command:
        cmd: "{{ temp_dir.path }}/find-efi-partition.sh /dev/{{ largest_disk.key }}"
      register: efi_part
      changed_when: false

    - name: Create UEFI boot entry for Flatcar
      ansible.builtin.command:
        cmd: "{{ temp_dir.path }}/create-flatcar-boot.sh /dev/{{ largest_disk.key }} {{ efi_part.stdout }}"
      register: boot_setup
      changed_when: boot_setup.stdout != ""

    - name: Display pre-reboot message
      ansible.builtin.debug:
        msg: >-
          Installation complete! Rebooting into Flatcar Container Linux.
          IMPORTANT: Unplug the rescue USB drive to ensure reboot does not reactive the rescue system.

    - name: Reboot the system
      ansible.builtin.command:
        cmd: "reboot now"
      async: 1
      poll: 0
      changed_when: true
