---
- name: Install Flatcar Container Linux
  hosts: rescue
  become: true
  vars:
    flatcar_script_url: "https://raw.githubusercontent.com/flatcar/init/3d2f9c6d778b96b08ee7db661bb2af1a6a42679d/bin/flatcar-install"
    flatcar_script_path: "/tmp/flatcar-install"
  tasks:
    - name: Update package repositories
      community.general.apk:
        update_cache: yes

    - name: Install flatcar-install script dependencies
      community.general.apk:
        name:
          - bash
          - bzip2
          - lsblk
          - eudev
          - gpg
          - gawk
        state: present
